### ISSUE TITLE
missing promotion in `gaussjacobi` for integer `α, β`

### ISSUE THREAD

**Issue by stevengj** [JuliaApproximation/FastGaussQuadrature.jl#117]
This works:
```jl
julia> gaussjacobi(500, 0.0, -1/2);
```
but changing `0.0` to an `Int` gives an error, probably indicating a missing call to `float(α)` or similar:
```jl
julia> gaussjacobi(500, 0, -1/2)
ERROR: MethodError: no method matching asy1(::Int64, ::Int64, ::Float64, ::Int64)
Closest candidates are:
  asy1(::Integer, ::Float64, ::Float64, ::Integer) at ~/.julia/packages/FastGaussQuadrature/BRLTf/src/gaussjacobi.jl:200
Stacktrace:
 [1] jacobi_asy(n::Int64, α::Int64, β::Float64)
   @ FastGaussQuadrature ~/.julia/packages/FastGaussQuadrature/BRLTf/src/gaussjacobi.jl:183
 [2] gaussjacobi(n::Int64, α::Int64, β::Float64)
   @ FastGaussQuadrature ~/.julia/packages/FastGaussQuadrature/BRLTf/src/gaussjacobi.jl:45
 [3] top-level scope
   @ REPL[98]:1
```

**Comment by dlfivefifty** [comment]
`jacobi_asy` should be restricted to `Float64` as the choice of boundary terms is precision dependent:

https://github.com/JuliaApproximation/FastGaussQuadrature.jl/blob/8b964b712a4beb4403b984311da59748af2d7b70/src/gaussjacobi.jl#L175

It would be easy to add a `promote` for the case of differing types of course.

**Comment by stevengj** [comment]
Maybe `promote(float(α), float(β))...` since passing integers should be allowed.
