### ISSUE TITLE
Question: automatic integration

### ISSUE THREAD

**Issue by dholladay00** [JuliaApproximation/FastGaussQuadrature.jl#51]
With these rules, one can increase quadrature order very easily and with very low memory requirements.

Any ideas on how to use these efficiently in an automatic integrator? (I would like to be able to specify a tolerance and receive an estimate of the integral w/in that tolerance, but accurate error estimation is difficult.) I have not been able to obtain similar performance to spatially adaptive, fixed order quadratures. 

Has anyone investigated something along these lines?

**Comment by dlfivefifty** [comment]
Usually automatic integrators use low order quadrature rules on many small panels, with a focus on handling singularities, so it's not clear how useful fast high order quadrature schemes are.

In the case of Clenshaw-Curtis, you can use ApproxFuns adaptive constructor. But there is no error estimate.

**Comment by dholladay00** [comment]
The issue with the adaptive methods is that they can require lots of storage, something like (quadrature order) x (recursion depth). I am looking for something with similar speed and/or convergence properties, but with much smaller memory requirements. This is fine on multi-core CPUs, and it might be for many-core CPUs like intel Knight's Landing (though I haven't verified that yet). 

However, to run on the GPU, each thread in a warp has to compute an integral and so the I am very limited on memory. I tried Romberg integration, which had much lower memory requirements, but it turned out to be 70x slower, so I need to find the right balance. 

I'll take a look at Clenshaw-Curtis. Thanks for the info @dlfivefifty!!

**Comment by hyrodium** [comment]
This issue seems inactive, so I'll close this issue.
