### ISSUE TITLE
Loss of precision for weights of Gauss-Jacobi quadratures near boundary

### ISSUE THREAD

**Issue by JamesCBremerJr** [JuliaApproximation/FastGaussQuadrature.jl#58]
The weights of Gauss-Jacobi quadrature rule corresponding to points near the singularities at +-1 are not computed to high accuracy in all cases.

For example, for a = 0.25, b = 0.0 and n = 2^10, the weight corresponding to the node
closest to 1 is (to about 24 digit accuracy)

3.60755490460431077919218552192672111E-0007

while gaussjacobi returns

3.607554904543958d-7

This is roughly 10 digit accuracy.  For n=2^12, the weight for the node
closest to 1 is (to 24 digits or so) 

 1.12865287559907169561093365173501611E-0008

while gaussjacobi returns

1.12865287520011950000000000000000002E-0008.

This is an error of about 3.53x10^(-10).  The MATLAB version of the code included with chebfun achieves double precision accuracy.

**Comment by hyrodium** [comment]
Fixed by https://github.com/JuliaApproximation/FastGaussQuadrature.jl/pull/131.
