### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastGaussQuadrature.jl#66]
```julia
help?> gaussjacobi
search: gaussjacobi

  No documentation found.

  FastGaussQuadrature.gaussjacobi is a Function.

  # 2 methods for generic function "gaussjacobi":
  [1] gaussjacobi(n::Integer, a::Float64, b::Float64) in FastGaussQuadrature at /Users/solver/.julia/packages/FastGaussQuadrature/G3Izs/src/gaussjacobi.jl:7
  [2] gaussjacobi(n::Number, a::Number, b::Number) in FastGaussQuadrature at /Users/solver/.julia/packages/FastGaussQuadrature/G3Izs/src/gaussjacobi.jl:1
```

**Comment by hyrodium** [comment]
Can I make a document with Documenter.jl?

**Comment by dlfivefifty** [comment]
To add help documentation you just add a string before the function definition: if in a file I write
```julia
# foo.jl
"""
foo(x) does nothing
"""
foo(x) = nothing
```
Then I get:
```julia
help?> foo
search: foo floor pointer_from_objref OverflowError RoundFromZero unsafe_copyto!

  foo(x) does nothing
```

**Comment by hyrodium** [comment]
Ah, I know that.

I was planning to add `jldoctest` for clarity. To check the tests, we need Documenter.jl. I thought this is a goot oppotunity to add more documents, but my concern was that adding Documenter.jl could be bigger change.

**Comment by dlfivefifty** [comment]
I strongly support adding Documenter.jl so will happily help

**Comment by hyrodium** [comment]
Okay, I'll make a pull request!

**Comment by hyrodium** [comment]
The github pages works fine, so I'll close this issue.
https://juliaapproximation.github.io/FastGaussQuadrature.jl/dev/

**Comment by dlfivefifty** [comment]
Awesome!! Thank so much for this
