### ISSUE TITLE
Move to JuliaApproximation?

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaApproximation/FastGaussQuadrature.jl#70]
Maybe it's time to move this to JuliaApproximation? The benefit is that any "member" can merge PRs, tag new releases, etc., which eases the burden of maintenance. This will help prevent PRs sitting for too long waiting for a response.

@ajt60gaibb Any opinions on this?

**Comment by ajt60gaibb** [comment]
Sure, it makes sense to move it.

**Comment by dlfivefifty** [comment]
OK I think you'll have to transfer it in settings
