### ISSUE TITLE
Is CI (Travis) set up correctly?

### ISSUE THREAD

**Issue by tpapp** [JuliaApproximation/FastGaussQuadrature.jl#72]
I don't see any builds, and I am not even sure it is enabled for this repository.

(I am asking because I would like to contribute PRs).

**Comment by hyrodium** [comment]
I think this issue is already solved.

Travis CI:
https://travis-ci.org/github/JuliaApproximation/FastGaussQuadrature.jl

Maybe this commit is related:
https://github.com/JuliaApproximation/FastGaussQuadrature.jl/commit/af2a9a3713e7b20fa7c22b68b024c06f999ba8da
