### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by arnavs** [JuliaApproximation/FastGaussQuadrature.jl#77]
I want to cite this library in a JOSS paper. 

How should I do so? Currently I just mentioned it, and then picked a random Olver, Townsend et al paper on quadrature to cite/mention it.

**Comment by dlfivefifty** [comment]
Probably Hale & Townsend 2013 (https://epubs.siam.org/doi/pdf/10.1137/120889873) is most relevant for Gauss–Legendre, but other publications are Townsend, Trogdon, & Olver 2016 (https://academic.oup.com/imajna/article-abstract/36/1/337/2363694) for Gauss–Hermite.

**Comment by dlfivefifty** [comment]
Oh but I guess Gauss–Legendre is actually Bogaert, "Iteration-free computation of Gauss-Legendre quadrature nodes and weights", SIAM J. Sci. Comput., 36(3), A1008-A1026, 2014.

**Comment by arnavs** [comment]
Yeah the Trogdon one is the one I cited. Cool
