### ISSUE TITLE
Package build failed on Windows (Julia v1.3.1)

### ISSUE THREAD

**Issue by rrhiemstra** [JuliaApproximation/FastGaussQuadrature.jl#78]
I am getting the followin error trace when I try to install the package.

julia> Pkg.add("FastGaussQuadrature")
  Updating registry at `C:\Users\rene\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
tar: jl_EDBB.tmp: Couldn't find file: Permission denied
tar: Error exit delayed from previous errors.
ERROR: Unable to automatically install 'OpenSpecFun' from 'C:\Users\rene\.julia\packages\OpenSpecFun_jll\XrUb6\Artifacts.toml'
Stacktrace:

**Comment by dlfivefifty** [comment]
This doesn’t seem to be related to this package. Perhaps try deleting your .julia?

**Comment by hyrodium** [comment]
The CI testing for Windows works fine, and this issue seems not active.
So, I'll close this issue.
