### ISSUE TITLE
Estimate/Upper Bound for Integration error

### ISSUE THREAD

**Issue by freemin7** [JuliaApproximation/FastGaussQuadrature.jl#79]
Hi

i just wanted to ask whether it aligns with the philosophy of packet to provide error estimates or if i should should stick with QuadGK.jl

**Comment by dlfivefifty** [comment]
That seems separate: this package allows the fast creation of Gauss quadrature rules but does not do adaptive quadrature. 

(Error estimates typically involve evaluating at multiple grids, though there are other methods, e.g., looking at decay in expansion coefficients or auto-differentiation to get rigorous bounds on derivatives.)

**Comment by freemin7** [comment]
Thanks
