### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by ranocha** [JuliaApproximation/FastGaussQuadrature.jl#82]
I noticed that this repo still uses travic-ci.org, at least based on the badge in the README. travis-ci.org will be shut down at the end of the year, cf. https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom. Hence, everything should be migrated to travis-ci.com.

The Travis badge in the README is currently broken since it points to `ajt60gaibb/FastGaussQuadrature.jl` instead of `JuliaApproximation/FastGaussQuadrature.jl`.

**Comment by hyrodium** [comment]
>The Travis badge in the README is currently broken since it points to ajt60gaibb/FastGaussQuadrature.jl instead of JuliaApproximation/FastGaussQuadrature.jl.

This is already solved by this commit.
https://github.com/JuliaApproximation/FastGaussQuadrature.jl/commit/af2a9a3713e7b20fa7c22b68b024c06f999ba8da

>everything should be migrated to travis-ci.com.

That's right.
@dlfivefifty Could you try migrating?
https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by dlfivefifty** [comment]
Not sure what's left to do, this seems to work: https://travis-ci.com/github/dlfivefifty/FastGaussQuadrature.jl

**Comment by dlfivefifty** [comment]
OK I clicked "Migrate" so hopefully that's enough?

https://travis-ci.com/github/JuliaApproximation/FastGaussQuadrature.jl

**Comment by hyrodium** [comment]
Thanks!
I'll fix it within #87.
