### ISSUE TITLE
Piessens's Chebyshev series approximations doesn't have enough accurate

### ISSUE THREAD

**Issue by hyrodium** [JuliaApproximation/FastGaussQuadrature.jl#91]
The first 6 roots of Bessel function are calculated by Piessens's Chebyshev series approximations, but the results seems not accurate.

```julia
julia> using FastGaussQuadrature, SpecialFunctions

julia> ν = 0.3;

julia> roots = besselroots(ν, 10);

julia> (x -> besselj(ν, x)).(roots)
10-element Array{Float64,1}:
  6.718603471017997e-13
 -3.435674124127745e-13
  2.7793746255620393e-13
 -5.53975336840582e-14
  8.078408461710157e-14
  1.0039082407550601e-13
 -8.703782704856492e-16
  2.699987915177195e-16
  7.404077679642275e-17
  1.4518249909932385e-16
```

https://github.com/JuliaApproximation/FastGaussQuadrature.jl/blob/master/src/besselroots.jl#L133

I think the hard-coded `const Piessens_C` is suspicious because lower right part seems ideally non-zero.
![image](https://user-images.githubusercontent.com/7488140/104089219-68266300-52b0-11eb-87c7-353492c1341d.png)

**Comment by hyrodium** [comment]
sorry, I overlooked this comment:
```julia
#   -1 ≤ ν ≤ 5 : ν ~= 0 --> 12 decimal figures for the 6 first zeros
#     (Piessens's Chebyshev series approximations)
```

https://github.com/JuliaApproximation/FastGaussQuadrature.jl/blob/master/src/besselroots.jl#L31

**Comment by hyrodium** [comment]
Ah, the `besselroots` function is used only for the initial values of the Newton's method, so we don't care about its accuracy.
Should we make the function private?

**Comment by dlfivefifty** [comment]
May also rename it `approx_besselroots` to avoid confusion

**Comment by hyrodium** [comment]
close this issue by renaming to `approx_besselroots` (#96).
