### ISSUE TITLE
Quadrature rules for the weight function w(x) = 1/(1+x^2)

### ISSUE THREAD

**Issue by nhavt** [JuliaApproximation/FastGaussQuadrature.jl#98]
Hi there,

I am looking for a quadrature rule that supports the weight w(x) = 1/(1+x^2). So could you please tell me whether I can find your package? Thank you very much in advance.

**Comment by dlfivefifty** [comment]
No we only have classical cases

ClassicalOrthogonalPolynomials.up can do this

**Comment by nhavt** [comment]
Hi dlfivefifty, that is great! Thank you very much for looking at my issue. I look forward to seeing your code.

**Comment by dlfivefifty** [comment]
Sorry need to tag some bug fixes but once that's done the following code works:
```julia
julia> x = axes(Legendre(),1)
Inclusion(-1.0..1.0 (Chebyshev))

julia> Q = LanczosPolynomial(inv.(1 .+ x.^2));

julia> x,w = ClassicalOrthogonalPolynomials.golubwelsch(Q[:,Base.OneTo(10)])
([-0.9724303119085456, -0.858355460511601, -0.667296759861326, -0.42080409420924214, -0.14339095204048347, 0.14339095204048447, 0.42080409420924336, 0.6672967598613262, 0.8583554605116023, 0.9724303119085471], [0.03615028973210828, 0.08958952909454486, 0.15418172912568381, 0.22593495363521388, 0.2795416618098968, 0.27954166180989914, 0.2259349536352133, 0.15418172912568348, 0.08958952909454379, 0.03615028973210902])
```

**Comment by nhavt** [comment]
Hi @dlfivefifty, thank you very much for your response. There is no rush on this. I can wait a bit. Also, could you please tell me a bit about "LanczosPolynomial" since this is new to me? Does that refer to this work, https://core.ac.uk/download/pdf/82178243.pdf?

**Comment by dlfivefifty** [comment]
Just means OPs w.r.t. `w` (The "Lanczos" refers to the fact that the algorithm used is lanczos with a different inner product, but this is basically equivalent to the Stieltjes procedure. Actually its likely to switch to a cholesky...)

**Comment by nhavt** [comment]
yes, thank you for your explanation. Could you please tell me the references that you use to implement the algorithm?

**Comment by dlfivefifty** [comment]
http://approximatelyfunctioning.blogspot.com/2020/09/quasi-matrices-orthogonal-polynomials.html

**Comment by nhavt** [comment]
Thank you!
